areas:
  - name: enemy_danger
    type: forbidden
    points:
      - [1.0, 1.0]
      - [3.0, 1.0]
      - [3.0, 3.0]
      - [1.0, 3.0]

  - name: patrol_area
    type: patrol
    points:
      - [-1.0, -1.0]
      - [0.0, -1.0]
      - [0.0, 0.0]
      - [-1.0, 0.0]
